# Generated by Django 5.0.3 on 2024-03-20 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libreria',
            old_name='ariticulo',
            new_name='articulo',
        ),
    ]
